import type { IngredientOption } from './definitions';

export const coffeeBeans: IngredientOption[] = [
  { label: 'Arabica', value: 'arabica', scores: { acidity: 2, body: 1, caffeine: 2, aroma: 3 } },
  { label: 'Robusta', value: 'robusta', scores: { bitterness: 3, body: 3, caffeine: 4 } },
  { label: 'Liberica', value: 'liberica', scores: { sweetness: 1, bitterness: 2, body: 2, aroma: 1 } },
  { label: 'Excelsa', value: 'excelsa', scores: { acidity: 2, bitterness: 1, body: 1 } },
];

export const roastLevels: IngredientOption[] = [
  { label: 'Light', value: 'light', scores: { acidity: 3, bitterness: 1, body: 1, aroma: 2 } },
  { label: 'Medium', value: 'medium', scores: { sweetness: 1, acidity: 1, bitterness: 2, body: 2, aroma: 1 } },
  { label: 'Dark', value: 'dark', scores: { bitterness: 3, body: 3, aroma: -1 } },
];

export const brewingMethods: IngredientOption[] = [
  { label: 'Espresso', value: 'espresso', scores: { bitterness: 2, body: 3, caffeine: 3, aftertaste: 2 } },
  { label: 'Pour Over', value: 'pour-over', scores: { acidity: 2, body: -1, aroma: 2, aftertaste: 1 } },
  { label: 'French Press', value: 'french-press', scores: { bitterness: 1, body: 2, aftertaste: 1 } },
  { label: 'Cold Brew', value: 'cold-brew', scores: { sweetness: 1, bitterness: -2, acidity: -2, caffeine: 3 } },
];

export const milks: IngredientOption[] = [
  { label: 'None', value: 'none', scores: {} },
  {
    label: 'Whole Milk',
    value: 'whole-milk',
    scores: { sweetness: 1, body: 1, acidity: -1 },
    brands: [
        { label: 'Greenfields', value: 'greenfields', scores: { body: 1, sweetness: 1, aftertaste: 1 } },
        { label: 'Ultra Milk', value: 'ultra-milk', scores: { body: 0, sweetness: 2 } },
    ]
  },
  {
    label: 'SKM',
    value: 'skm',
    scores: { sweetness: 3, body: 2, acidity: -1 },
    brands: [
        { label: 'Frisian Flag', value: 'frisian-flag', scores: { sweetness: 2, body: 1 } },
        { label: 'Indomilk', value: 'indomilk', scores: { sweetness: 2 } }
    ]
  },
  { 
    label: 'Oat Milk', 
    value: 'oat-milk', 
    scores: { sweetness: 2, body: 0 },
    brands: [
        { label: 'Oatly', value: 'oatly', scores: { sweetness: 1, body: 1 } }
    ]
  },
  { 
    label: 'Almond Milk', 
    value: 'almond-milk', 
    scores: { sweetness: 1, aroma: 1 },
    brands: [
        { label: 'Alpro', value: 'alpro', scores: { sweetness: 1, aroma: 0 } }
    ]
  },
];

const creamerBrands = [
  { label: 'Coffeemate', value: 'coffeemate', scores: { sweetness: 1, body: 2 } },
  { label: 'Indocafe Creamer', value: 'indocafe', scores: { body: 1 } },
];

export const creamers: IngredientOption[] = [
  { label: 'None', value: 'none', scores: {} },
  { label: 'Original', value: 'original', scores: { sweetness: 2, body: 1 }, brands: creamerBrands },
  { label: 'Sweet Cream', value: 'sweet-cream', scores: { sweetness: 3, body: 2 }, brands: creamerBrands },
  { label: 'French Vanilla', value: 'french-vanilla-creamer', scores: { sweetness: 3, aroma: 3, body: 1 }, brands: creamerBrands },
  { label: 'Vanilla Bean', value: 'vanilla-bean', scores: { sweetness: 3, aroma: 4 }, brands: creamerBrands },
  { label: 'Caramel', value: 'caramel-creamer', scores: { sweetness: 4, aftertaste: 2 }, brands: creamerBrands },
  { label: 'Salted Caramel', value: 'salted-caramel-creamer', scores: { sweetness: 3, body: 1, aftertaste: 2 }, brands: creamerBrands },
  { label: 'Hazelnut', value: 'hazelnut-creamer', scores: { sweetness: 2, aroma: 3, aftertaste: 1 }, brands: creamerBrands },
  { label: 'Toffee Nut', value: 'toffee-nut-creamer', scores: { sweetness: 4, aroma: 3, body: 1 }, brands: creamerBrands },
  { label: 'Irish Cream', value: 'irish-cream-creamer', scores: { sweetness: 4, body: 2, aroma: 2 }, brands: creamerBrands },
  { label: 'Crème Brûlée', value: 'creme-brulee-creamer', scores: { sweetness: 5, body: 1, aroma: 2 }, brands: creamerBrands },
  { label: 'Butter Pecan', value: 'butter-pecan-creamer', scores: { sweetness: 4, aroma: 3, body: 1 }, brands: creamerBrands },
  { label: 'Amaretto', value: 'amaretto-creamer', scores: { sweetness: 4, aroma: 4 }, brands: creamerBrands },
  { label: 'Chocolate', value: 'chocolate-creamer', scores: { sweetness: 3, bitterness: 1 }, brands: creamerBrands },
  { label: 'Mocha', value: 'mocha-creamer', scores: { sweetness: 3, bitterness: 1, body: 1 }, brands: creamerBrands },
  { label: 'White Chocolate', value: 'white-chocolate-creamer', scores: { sweetness: 5, body: 1 }, brands: creamerBrands },
  { label: 'Chocolate Hazelnut', value: 'chocolate-hazelnut', scores: { sweetness: 4, aroma: 3, bitterness: 1 }, brands: creamerBrands },
  { label: 'Toffee', value: 'toffee', scores: { sweetness: 5 }, brands: creamerBrands },
  { label: 'Butterscotch', value: 'butterscotch-creamer', scores: { sweetness: 5, body: 1 }, brands: creamerBrands },
  { label: 'Cookies & Cream', value: 'cookies-cream-creamer', scores: { sweetness: 5, body: 1, aroma: 2 }, brands: creamerBrands },
  { label: 'Cookie Dough', value: 'cookie-dough-creamer', scores: { sweetness: 5, body: 1 }, brands: creamerBrands },
  { label: 'Cinnamon', value: 'cinnamon-creamer', scores: { sweetness: 2, aroma: 4, aftertaste: 2 }, brands: creamerBrands },
  { label: 'Cinnamon Roll', value: 'cinnamon-roll-creamer', scores: { sweetness: 5, aroma: 4, body: 1 }, brands: creamerBrands },
  { label: 'Pumpkin Spice', value: 'pumpkin-spice-creamer', scores: { sweetness: 3, aroma: 4, body: 1 }, brands: creamerBrands },
  { label: 'Peppermint Mocha', value: 'peppermint-mocha', scores: { sweetness: 4, aroma: 4, bitterness: 1 }, brands: creamerBrands },
  { label: 'Peppermint', value: 'peppermint-creamer', scores: { sweetness: 3, aroma: 5, aftertaste: 3 }, brands: creamerBrands },
  { label: 'Mint Chocolate', value: 'mint-chocolate', scores: { sweetness: 4, aroma: 4, bitterness: 1 }, brands: creamerBrands },
  { label: 'Maple', value: 'maple-creamer', scores: { sweetness: 5, aroma: 2 }, brands: creamerBrands },
  { label: 'Maple Pecan', value: 'maple-pecan-creamer', scores: { sweetness: 5, aroma: 3 }, brands: creamerBrands },
  { label: 'Honey', value: 'honey-creamer', scores: { sweetness: 4, aroma: 1, aftertaste: 1 }, brands: creamerBrands },
  { label: 'Honey Vanilla', value: 'honey-vanilla', scores: { sweetness: 4, aroma: 2 }, brands: creamerBrands },
  { label: 'Vanilla Caramel', value: 'vanilla-caramel', scores: { sweetness: 5, aroma: 2 }, brands: creamerBrands },
  { label: 'Coconut', value: 'coconut-creamer', scores: { sweetness: 3, aroma: 3 }, brands: creamerBrands },
  { label: 'Coconut Cream', value: 'coconut-cream', scores: { sweetness: 3, aroma: 3, body: 1 }, brands: creamerBrands },
  { label: 'Coconut Caramel', value: 'coconut-caramel', scores: { sweetness: 4, aroma: 2 }, brands: creamerBrands },
  { label: 'Almond', value: 'almond-creamer', scores: { sweetness: 3, aroma: 3 }, brands: creamerBrands },
  { label: 'Almond Vanilla', value: 'almond-vanilla', scores: { sweetness: 3, aroma: 4 }, brands: creamerBrands },
  { label: 'Almond Caramel', value: 'almond-caramel', scores: { sweetness: 4, aroma: 2 }, brands: creamerBrands },
  { label: 'Oat Sweet Cream', value: 'oat-sweet-cream', scores: { sweetness: 3, body: 1 }, brands: creamerBrands },
  { label: 'Oat Vanilla', value: 'oat-vanilla', scores: { sweetness: 3, aroma: 3 }, brands: creamerBrands },
  { label: 'Oat Hazelnut', value: 'oat-hazelnut', scores: { sweetness: 2, aroma: 4 }, brands: creamerBrands },
  { label: 'Macadamia Nut', value: 'macadamia-nut-creamer', scores: { sweetness: 3, aroma: 3, body: 1 }, brands: creamerBrands },
  { label: 'Pistachio', value: 'pistachio-creamer', scores: { sweetness: 3, aroma: 3 }, brands: creamerBrands },
  { label: 'Brown Sugar', value: 'brown-sugar', scores: { sweetness: 4 }, brands: creamerBrands },
  { label: 'Brown Sugar Cinnamon', value: 'brown-sugar-cinnamon-creamer', scores: { sweetness: 4, aroma: 3 }, brands: creamerBrands },
  { label: 'Chai Spice', value: 'chai-spice-creamer', scores: { sweetness: 2, aroma: 5, aftertaste: 2 }, brands: creamerBrands },
  { label: 'Tiramisu', value: 'tiramisu-creamer', scores: { sweetness: 4, bitterness: 1, body: 2, aroma: 3 }, brands: creamerBrands },
  { label: 'S’mores', value: 'smores-creamer', scores: { sweetness: 5, body: 1, aroma: 2 }, brands: creamerBrands },
  { label: 'Marshmallow', value: 'marshmallow-creamer', scores: { sweetness: 5, body: 1, aroma: 1 }, brands: creamerBrands },
  { label: 'Toasted Marshmallow', value: 'toasted-marshmallow-creamer', scores: { sweetness: 5, aroma: 3 }, brands: creamerBrands },
  { label: 'Cotton Candy', value: 'cotton-candy-creamer', scores: { sweetness: 6, aroma: 1 }, brands: creamerBrands },
  { label: 'Birthday Cake', value: 'birthday-cake', scores: { sweetness: 6, aroma: 2 }, brands: creamerBrands },
  { label: 'Sugar Cookie', value: 'sugar-cookie', scores: { sweetness: 5 }, brands: creamerBrands },
  { label: 'Vanilla Bourbon', value: 'vanilla-bourbon', scores: { sweetness: 4, aroma: 4, body: 1 }, brands: creamerBrands },
  { label: 'Vanilla Latte', value: 'vanilla-latte', scores: { sweetness: 4, caffeine: 1 }, brands: creamerBrands },
  { label: 'Caramel Latte', value: 'caramel-latte', scores: { sweetness: 5, caffeine: 1 }, brands: creamerBrands },
  { label: 'Caramel Macchiato', value: 'caramel-macchiato', scores: { sweetness: 5, body: 1, caffeine: 1 }, brands: creamerBrands },
  { label: 'Mocha Latte', value: 'mocha-latte', scores: { sweetness: 4, bitterness: 1, caffeine: 1 }, brands: creamerBrands },
  { label: 'Chocolate Truffle', value: 'chocolate-truffle', scores: { sweetness: 5, bitterness: 2, body: 2 }, brands: creamerBrands },
  { label: 'Chocolate Mocha', value: 'chocolate-mocha', scores: { sweetness: 4, bitterness: 1, body: 1, caffeine: 1 }, brands: creamerBrands },
  { label: 'White Chocolate Raspberry', value: 'white-chocolate-raspberry-creamer', scores: { sweetness: 5, acidity: 1, aroma: 2 }, brands: creamerBrands },
  { label: 'Raspberry Cheesecake', value: 'raspberry-cheesecake', scores: { sweetness: 5, acidity: 1, body: 1 }, brands: creamerBrands },
  { label: 'Strawberry Cream', value: 'strawberry-cream', scores: { sweetness: 5, acidity: 1 }, brands: creamerBrands },
  { label: 'Banana Cream', value: 'banana-cream', scores: { sweetness: 5, aroma: 2 }, brands: creamerBrands },
  { label: 'Coconut Mocha', value: 'coconut-mocha', scores: { sweetness: 4, aroma: 3, bitterness: 1 }, brands: creamerBrands },
  { label: 'Maple Walnut', value: 'maple-walnut', scores: { sweetness: 5, aroma: 2 }, brands: creamerBrands },
  { label: 'Vanilla Almond', value: 'vanilla-almond', scores: { sweetness: 4, aroma: 4 }, brands: creamerBrands },
  { label: 'Coffeehouse Blend', value: 'coffeehouse-blend', scores: { body: 1, caffeine: 1 }, brands: creamerBrands },
  { label: 'Classic Cream', value: 'classic-cream', scores: { body: 2 }, brands: creamerBrands },
  { label: 'Velvety Cream', value: 'velvety-cream', scores: { body: 3 }, brands: creamerBrands },
  { label: 'Oat & Almond Blend', value: 'oat-almond-blend', scores: { body: 1, sweetness: 2 }, brands: creamerBrands },
  { label: 'Coconut & Caramel Blend', value: 'coconut-caramel-blend', scores: { sweetness: 4, aroma: 3 }, brands: creamerBrands },
  { label: 'Zero Sugar Vanilla', value: 'zero-sugar-vanilla', scores: { sweetness: 1, aroma: 3 }, brands: creamerBrands },
  { label: 'Zero Sugar Hazelnut', value: 'zero-sugar-hazelnut', scores: { sweetness: 1, aroma: 3 }, brands: creamerBrands },
  { label: 'Zero Sugar Caramel', value: 'zero-sugar-caramel', scores: { sweetness: 1 }, brands: creamerBrands },
  { label: 'Zero Sugar Sweet Cream', value: 'zero-sugar-sweet-cream', scores: { sweetness: 1, body: 2 }, brands: creamerBrands },
];

const syrupBrands = [
  { label: 'Monin', value: 'monin', scores: { sweetness: 1, aroma: 1, aftertaste: 1 } },
  { label: 'DaVinci', value: 'davinci', scores: { sweetness: 2, aftertaste: -1 } },
  { label: 'Torani', value: 'torani', scores: { sweetness: 1, aroma: -1, aftertaste: -1 } },
  { label: 'Ghirardelli', value: 'ghirardelli', scores: { body: 1, aftertaste: 1, bitterness: 1 } },
];

export const syrups: IngredientOption[] = [
  { label: 'None', value: 'none', scores: {} },
  { label: 'Vanilla', value: 'vanilla-syrup', scores: { sweetness: 4, aroma: 3 }, brands: syrupBrands },
  { label: 'French Vanilla', value: 'french-vanilla-syrup', scores: { sweetness: 4, aroma: 4, body: 1 }, brands: syrupBrands },
  { label: 'Caramel', value: 'caramel-syrup', scores: { sweetness: 5, body: 1, aftertaste: 1 }, brands: syrupBrands },
  { label: 'Salted Caramel', value: 'salted-caramel-syrup', scores: { sweetness: 4, body: 1, aftertaste: 2 }, brands: syrupBrands },
  { label: 'Hazelnut', value: 'hazelnut-syrup', scores: { sweetness: 3, aroma: 4, aftertaste: 1 }, brands: syrupBrands },
  { label: 'Almond', value: 'almond-syrup', scores: { sweetness: 3, aroma: 3 }, brands: syrupBrands },
  { label: 'Macadamia Nut', value: 'macadamia-nut-syrup', scores: { sweetness: 3, aroma: 3, body: 1 }, brands: syrupBrands },
  { label: 'Toffee Nut', value: 'toffee-nut-syrup', scores: { sweetness: 4, aroma: 3, body: 1 }, brands: syrupBrands },
  { label: 'Butterscotch', value: 'butterscotch-syrup', scores: { sweetness: 5, body: 1 }, brands: syrupBrands },
  { label: 'Irish Cream', value: 'irish-cream-syrup', scores: { sweetness: 4, body: 2, aroma: 2 }, brands: syrupBrands },
  { label: 'Mocha', value: 'mocha-syrup', scores: { sweetness: 3, bitterness: 1, body: 1 }, brands: syrupBrands },
  { label: 'White Chocolate', value: 'white-chocolate-syrup', scores: { sweetness: 5, body: 1 }, brands: syrupBrands },
  { label: 'Dark Chocolate', value: 'dark-chocolate-syrup', scores: { sweetness: 2, bitterness: 3, body: 1 }, brands: syrupBrands },
  { label: 'Milk Chocolate', value: 'milk-chocolate-syrup', scores: { sweetness: 4, bitterness: 1, body: 1 }, brands: syrupBrands },
  { label: 'Peppermint', value: 'peppermint-syrup', scores: { sweetness: 3, aroma: 5, aftertaste: 3 }, brands: syrupBrands },
  { label: 'Spearmint', value: 'spearmint-syrup', scores: { sweetness: 3, aroma: 4, aftertaste: 2 }, brands: syrupBrands },
  { label: 'Cinnamon', value: 'cinnamon-syrup', scores: { sweetness: 2, aroma: 4, aftertaste: 2 }, brands: syrupBrands },
  { label: 'Gingerbread', value: 'gingerbread-syrup', scores: { sweetness: 3, aroma: 4, aftertaste: 2 }, brands: syrupBrands },
  { label: 'Pumpkin Spice', value: 'pumpkin-spice-syrup', scores: { sweetness: 3, aroma: 4, body: 1 }, brands: syrupBrands },
  { label: 'Brown Sugar Cinnamon', value: 'brown-sugar-cinnamon-syrup', scores: { sweetness: 4, aroma: 3 }, brands: syrupBrands },
  { label: 'Maple', value: 'maple-syrup', scores: { sweetness: 5, aroma: 2 }, brands: syrupBrands },
  { label: 'Honey', value: 'honey-syrup', scores: { sweetness: 4, aroma: 1, aftertaste: 1 }, brands: syrupBrands },
  { label: 'Coconut', value: 'coconut-syrup', scores: { sweetness: 3, aroma: 3 }, brands: syrupBrands },
  { label: 'Banana', value: 'banana-syrup', scores: { sweetness: 4, aroma: 2 }, brands: syrupBrands },
  { label: 'Strawberry', value: 'strawberry-syrup', scores: { sweetness: 4, acidity: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Raspberry', value: 'raspberry-syrup', scores: { sweetness: 3, acidity: 2, aroma: 2 }, brands: syrupBrands },
  { label: 'Blueberry', value: 'blueberry-syrup', scores: { sweetness: 3, acidity: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Blackberry', value: 'blackberry-syrup', scores: { sweetness: 3, acidity: 1, aroma: 3 }, brands: syrupBrands },
  { label: 'Cherry', value: 'cherry-syrup', scores: { sweetness: 4, acidity: 1 }, brands: syrupBrands },
  { label: 'Peach', value: 'peach-syrup', scores: { sweetness: 4, acidity: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Mango', value: 'mango-syrup', scores: { sweetness: 5, acidity: 1, aroma: 3 }, brands: syrupBrands },
  { label: 'Pineapple', value: 'pineapple-syrup', scores: { sweetness: 4, acidity: 2, aroma: 2 }, brands: syrupBrands },
  { label: 'Passion Fruit', value: 'passion-fruit-syrup', scores: { sweetness: 4, acidity: 3, aroma: 3 }, brands: syrupBrands },
  { label: 'Lychee', value: 'lychee-syrup', scores: { sweetness: 4, aroma: 3 }, brands: syrupBrands },
  { label: 'Watermelon', value: 'watermelon-syrup', scores: { sweetness: 3, aroma: 1 }, brands: syrupBrands },
  { label: 'Kiwi', value: 'kiwi-syrup', scores: { sweetness: 3, acidity: 2 }, brands: syrupBrands },
  { label: 'Melon', value: 'melon-syrup', scores: { sweetness: 3, aroma: 1 }, brands: syrupBrands },
  { label: 'Apple', value: 'apple-syrup', scores: { sweetness: 3, acidity: 1 }, brands: syrupBrands },
  { label: 'Green Apple', value: 'green-apple-syrup', scores: { sweetness: 2, acidity: 3 }, brands: syrupBrands },
  { label: 'Lemon', value: 'lemon-syrup', scores: { sweetness: 2, acidity: 4 }, brands: syrupBrands },
  { label: 'Lime', value: 'lime-syrup', scores: { sweetness: 2, acidity: 4 }, brands: syrupBrands },
  { label: 'Orange', value: 'orange-syrup', scores: { sweetness: 3, acidity: 3 }, brands: syrupBrands },
  { label: 'Blood Orange', value: 'blood-orange-syrup', scores: { sweetness: 3, acidity: 3, bitterness: 1 }, brands: syrupBrands },
  { label: 'Grapefruit', value: 'grapefruit-syrup', scores: { sweetness: 2, acidity: 3, bitterness: 2 }, brands: syrupBrands },
  { label: 'Tiramisu', value: 'tiramisu-syrup', scores: { sweetness: 4, bitterness: 1, body: 2, aroma: 3 }, brands: syrupBrands },
  { label: 'Cookies & Cream', value: 'cookies-cream-syrup', scores: { sweetness: 5, body: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Cotton Candy', value: 'cotton-candy-syrup', scores: { sweetness: 6, aroma: 1 }, brands: syrupBrands },
  { label: 'Bubblegum', value: 'bubblegum-syrup', scores: { sweetness: 5, aroma: 2 }, brands: syrupBrands },
  { label: 'Marshmallow', value: 'marshmallow-syrup', scores: { sweetness: 5, body: 1, aroma: 1 }, brands: syrupBrands },
  { label: 'Pistachio', value: 'pistachio-syrup', scores: { sweetness: 3, aroma: 3 }, brands: syrupBrands },
  { label: 'Lavender', value: 'lavender-syrup', scores: { sweetness: 2, aroma: 4 }, brands: syrupBrands },
  { label: 'Rose', value: 'rose-syrup', scores: { sweetness: 2, aroma: 5 }, brands: syrupBrands },
  { label: 'Jasmine', value: 'jasmine-syrup', scores: { sweetness: 1, aroma: 5 }, brands: syrupBrands },
  { label: 'Hibiscus', value: 'hibiscus-syrup', scores: { sweetness: 2, acidity: 2, aroma: 3 }, brands: syrupBrands },
  { label: 'Cardamom', value: 'cardamom-syrup', scores: { sweetness: 1, aroma: 4, aftertaste: 2 }, brands: syrupBrands },
  { label: 'Chai Spice', value: 'chai-spice-syrup', scores: { sweetness: 2, aroma: 5, aftertaste: 2 }, brands: syrupBrands },
  { label: 'Cinnamon Roll', value: 'cinnamon-roll-syrup', scores: { sweetness: 5, aroma: 4, body: 1 }, brands: syrupBrands },
  { label: 'Butter Pecan', value: 'butter-pecan-syrup', scores: { sweetness: 4, aroma: 3, body: 1 }, brands: syrupBrands },
  { label: 'Almond Praline', value: 'almond-praline-syrup', scores: { sweetness: 5, aroma: 3 }, brands: syrupBrands },
  { label: 'Nougat', value: 'nougat-syrup', scores: { sweetness: 4, body: 1 }, brands: syrupBrands },
  { label: 'Crème Brûlée', value: 'creme-brulee-syrup', scores: { sweetness: 5, body: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Custard', value: 'custard-syrup', scores: { sweetness: 4, body: 2 }, brands: syrupBrands },
  { label: 'Biscuit', value: 'biscuit-syrup', scores: { sweetness: 2, body: 1 }, brands: syrupBrands },
  { label: 'Cookie Dough', value: 'cookie-dough-syrup', scores: { sweetness: 5, body: 1 }, brands: syrupBrands },
  { label: 'Maple Pecan', value: 'maple-pecan-syrup', scores: { sweetness: 5, aroma: 3 }, brands: syrupBrands },
  { label: 'Peanut Butter', value: 'peanut-butter-syrup', scores: { sweetness: 3, body: 2, aroma: 2 }, brands: syrupBrands },
  { label: 'S’mores', value: 'smores-syrup', scores: { sweetness: 5, body: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Candy Cane', value: 'candy-cane-syrup', scores: { sweetness: 4, aroma: 4 }, brands: syrupBrands },
  { label: 'Toasted Marshmallow', value: 'toasted-marshmallow-syrup', scores: { sweetness: 5, aroma: 3 }, brands: syrupBrands },
  { label: 'Chocolate Mint', value: 'chocolate-mint-syrup', scores: { sweetness: 4, aroma: 4, bitterness: 1 }, brands: syrupBrands },
  { label: 'Mocha Caramel', value: 'mocha-caramel-syrup', scores: { sweetness: 5, body: 1, bitterness: 1 }, brands: syrupBrands },
  { label: 'White Chocolate Raspberry', value: 'white-chocolate-raspberry-syrup', scores: { sweetness: 5, acidity: 1, aroma: 2 }, brands: syrupBrands },
  { label: 'Almond Toffee', value: 'almond-toffee-syrup', scores: { sweetness: 5, aroma: 2, body: 1 }, brands: syrupBrands },
  { label: 'Brownie Batter', value: 'brownie-batter-syrup', scores: { sweetness: 5, body: 2, bitterness: 1 }, brands: syrupBrands },
  { label: 'Honeycomb', value: 'honeycomb-syrup', scores: { sweetness: 6 }, brands: syrupBrands },
  { label: 'Coffee Liqueur', value: 'coffee-liqueur-syrup', scores: { sweetness: 3, bitterness: 2, body: 1, aroma: 3 }, brands: syrupBrands },
  { label: 'Amaretto', value: 'amaretto-syrup', scores: { sweetness: 4, aroma: 4 }, brands: syrupBrands },
  { label: 'Rum Caramel', value: 'rum-caramel-syrup', scores: { sweetness: 5, aroma: 3, body: 1 }, brands: syrupBrands },
  { label: 'Bourbon Vanilla', value: 'bourbon-vanilla-syrup', scores: { sweetness: 4, aroma: 4, body: 1 }, brands: syrupBrands },
  { label: 'Espresso Roast', value: 'espresso-roast-syrup', scores: { sweetness: 1, bitterness: 4, body: 2, aroma: 4 }, brands: syrupBrands },
];

export const toppings: IngredientOption[] = [
  { label: 'None', value: 'none', scores: {} },
  { label: 'Whipped Cream', value: 'whipped-cream', scores: { sweetness: 2, body: 1 } },
  {
    label: 'Chocolate Shavings',
    value: 'chocolate-shavings',
    scores: { sweetness: 1, bitterness: 1, aroma: 1 },
    brands: [
        { label: 'Van Houten', value: 'van-houten', scores: { bitterness: 1, body: 1 } },
        { label: 'Cadbury', value: 'cadbury', scores: { sweetness: 1 } },
    ]
  },
  { label: 'Cinnamon', value: 'cinnamon', scores: { aroma: 2, aftertaste: 1 } },
  {
    label: 'Caramel Drizzle',
    value: 'caramel-drizzle',
    scores: { sweetness: 3 },
    brands: [
        { label: 'Monin', value: 'monin-drizzle', scores: { sweetness: 1 } },
        { label: 'Ghirardelli', value: 'ghirardelli-drizzle', scores: { aftertaste: 1 } },
    ]
  },
];

export const ingredientCategories = {
  coffeeBeans,
  roastLevel: roastLevels,
  brewingMethod: brewingMethods,
  milk: milks,
  creamer: creamers,
  syrup: syrups,
  toppings: toppings,
};
