
import type { Recipe } from './definitions';

export const recipeTemplates: Omit<Recipe, 'id'>[] = [
  // 1. Turkish Coffee – Turkey
  {
    name: 'Turkish Coffee',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 7,
    roastLevel: 'dark',
    roastLevelAmount: 7,
    brewingMethod: 'turkish-coffee',
    brewingMethodAmount: 70,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'gula-pasir',
    sweetenerAmount: 5,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 2. Greek Coffee – Greece
  {
    name: 'Greek Coffee',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 8,
    roastLevel: 'light',
    roastLevelAmount: 8,
    brewingMethod: 'turkish-coffee', // Briki is similar to Cezve
    brewingMethodAmount: 75,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'gula-pasir',
    sweetenerAmount: 5,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 3. Arabic Coffee / Qahwa – Middle East
  {
    name: 'Arabic Coffee (Qahwa)',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 10,
    roastLevel: 'light',
    roastLevelAmount: 10,
    brewingMethod: 'qahwa',
    brewingMethodAmount: 100,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'cardamom-syrup', // Simulating cardamom spice
    syrupAmount: 5,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 4. Moroccan Coffee – Morocco
  {
    name: 'Moroccan Spiced Coffee',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 15,
    roastLevel: 'dark',
    roastLevelAmount: 15,
    brewingMethod: 'french-press', // Similar full-bodied style
    brewingMethodAmount: 180,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'cinnamon-syrup', // Representing spices
    syrupAmount: 10,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 5. Ethiopian Coffee – Ethiopia
  {
    name: 'Ethiopian Coffee (Jebena)',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 15,
    roastLevel: 'medium',
    roastLevelAmount: 15,
    brewingMethod: 'ethiopian-jebena',
    brewingMethodAmount: 150,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 6. Ethiopian Bunna Ceremony – Ethiopia
  {
    name: 'Ethiopian Bunna Ceremony Style',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 20,
    roastLevel: 'medium',
    roastLevelAmount: 20,
    brewingMethod: 'ethiopian-jebena',
    brewingMethodAmount: 200,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'sea-salt-flakes', // Often served with salt or butter
    toppingsAmount: 1,
  },
  // 7. Vietnamese Black Coffee (Phin Filter) – Vietnam
  {
    name: 'Vietnamese Black Coffee',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 20,
    roastLevel: 'dark',
    roastLevelAmount: 20,
    brewingMethod: 'vietnamese-drip',
    brewingMethodAmount: 80,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 8. Vietnamese Egg Coffee – Vietnam
  {
    name: 'Vietnamese Egg Coffee',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 15,
    roastLevel: 'dark',
    roastLevelAmount: 15,
    brewingMethod: 'vietnamese-drip',
    brewingMethodAmount: 60,
    milk: 'skm', // Condensed milk is key
    milkAmount: 20,
    creamer: 'custard-syrup', // To simulate egg yolk texture and taste
    creamerAmount: 20,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 9. Cuban Coffee / Café Cubano – Cuba
  {
    name: 'Café Cubano',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 18,
    roastLevel: 'dark',
    roastLevelAmount: 18,
    brewingMethod: 'cuban-coffee',
    brewingMethodAmount: 40,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'brown-sugar',
    sweetenerAmount: 15, // A lot of sugar is key
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 10. Café de Olla – Mexico
  {
    name: 'Café de Olla',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 20,
    roastLevel: 'medium',
    roastLevelAmount: 20,
    brewingMethod: 'kopi-tubruk', // Clay pot boiling is similar to cowboy coffee
    brewingMethodAmount: 200,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'cinnamon-syrup',
    syrupAmount: 15,
    sweetener: 'gula-aren-cair', // Piloncillo is similar to gula aren
    sweetenerAmount: 20,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 31. Indonesian Kopi Tubruk – Indonesia
  {
    name: 'Kopi Tubruk',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 10,
    roastLevel: 'dark',
    roastLevelAmount: 10,
    brewingMethod: 'kopi-tubruk',
    brewingMethodAmount: 150,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'gula-pasir',
    sweetenerAmount: 10,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 32. Indonesian Kopi Talua – West Sumatra
  {
    name: 'Kopi Talua',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 12,
    roastLevel: 'dark',
    roastLevelAmount: 12,
    brewingMethod: 'kopi-tubruk',
    brewingMethodAmount: 120,
    milk: 'skm',
    milkAmount: 30,
    creamer: 'custard-syrup', // To simulate egg yolk
    creamerAmount: 25,
    syrup: 'cinnamon-syrup',
    syrupAmount: 5,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 33. Indonesian Kopi Jahe – Java
  {
    name: 'Kopi Jahe',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 10,
    roastLevel: 'medium',
    roastLevelAmount: 10,
    brewingMethod: 'kopi-tubruk',
    brewingMethodAmount: 180,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'gingerbread-syrup', // To simulate ginger
    syrupAmount: 15,
    sweetener: 'gula-merah-cair',
    sweetenerAmount: 10,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 34. Indonesian Kopi Rempah – Nusantara
  {
    name: 'Kopi Rempah',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 15,
    roastLevel: 'medium',
    roastLevelAmount: 15,
    brewingMethod: 'kopi-tubruk',
    brewingMethodAmount: 180,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'chai-spice-syrup', // Best representation for mixed spices
    syrupAmount: 20,
    sweetener: 'gula-aren-cair',
    sweetenerAmount: 10,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 35. Indonesian Kopi Joss – Yogyakarta
  {
    name: 'Kopi Joss',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 12,
    roastLevel: 'dark',
    roastLevelAmount: 12,
    brewingMethod: 'kopi-tubruk',
    brewingMethodAmount: 150,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'gula-pasir',
    sweetenerAmount: 15,
    toppings: 'none', // Charcoal is not an option, unfortunately
    toppingsAmount: 0,
  },
  // 36. Indonesian Kopi Saring – Aceh
  {
    name: 'Kopi Saring Aceh',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 20,
    roastLevel: 'dark',
    roastLevelAmount: 20,
    brewingMethod: 'nel-drip', // Simulates the cloth filter pull
    brewingMethodAmount: 120,
    milk: 'skm',
    milkAmount: 40,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 37. Indonesian Kopi Luwak – Sumatra
  {
    name: 'Kopi Luwak',
    coffeeBeans: 'arabica', // Luwak coffee is often Arabica
    coffeeBeansAmount: 15,
    roastLevel: 'medium',
    roastLevelAmount: 15,
    brewingMethod: 'pour-over-v60', // A clean method to appreciate its unique profile
    brewingMethodAmount: 220,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 38. Indonesian Kopi Kintamani – Bali
  {
    name: 'Kopi Kintamani',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 18,
    roastLevel: 'light',
    roastLevelAmount: 18,
    brewingMethod: 'pour-over-v60',
    brewingMethodAmount: 250,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'orange-syrup', // Kintamani is known for its citrus notes
    syrupAmount: 5,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 39. Indonesian Kopi Mandailing – North Sumatra
  {
    name: 'Kopi Mandailing',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 20,
    roastLevel: 'dark',
    roastLevelAmount: 20,
    brewingMethod: 'french-press', // To emphasize its heavy body
    brewingMethodAmount: 250,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'dark-chocolate-syrup', // Matches its earthy and chocolatey notes
    syrupAmount: 5,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 40. Indonesian Kopi Toraja – Sulawesi
  {
    name: 'Kopi Toraja',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 18,
    roastLevel: 'medium',
    roastLevelAmount: 18,
    brewingMethod: 'pour-over-v60',
    brewingMethodAmount: 250,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 70. Russian Traditional Coffee (Kawa-style) – Recommended
  {
    name: 'Russian Kawa-style Coffee',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 10,
    roastLevel: 'dark',
    roastLevelAmount: 10,
    brewingMethod: 'turkish-coffee', // Similar preparation
    brewingMethodAmount: 100,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'lemon-syrup', // Often served with lemon
    syrupAmount: 5,
    sweetener: 'honey',
    sweetenerAmount: 10,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 11. Swedish Bryggkaffe
  {
    name: 'Swedish Bryggkaffe',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 20,
    roastLevel: 'light',
    roastLevelAmount: 20,
    brewingMethod: 'auto-drip',
    brewingMethodAmount: 300,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 12. Finnish Kaffeost
  {
    name: 'Finnish Kaffeost',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 15,
    roastLevel: 'light',
    roastLevelAmount: 15,
    brewingMethod: 'pour-over-v60',
    brewingMethodAmount: 200,
    milk: 'none',
    milkAmount: 0,
    creamer: 'original', // To simulate cheese curds (Leipäjuusto)
    creamerAmount: 30,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 13. Brazilian Cafezinho
  {
    name: 'Brazilian Cafezinho',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 10,
    roastLevel: 'dark',
    roastLevelAmount: 10,
    brewingMethod: 'nel-drip', // Filtered, strong
    brewingMethodAmount: 60,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'gula-pasir', // Heavily sweetened
    sweetenerAmount: 15,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 14. Colombian Traditional Brew
  {
    name: 'Colombian Tinto',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 10,
    roastLevel: 'medium',
    roastLevelAmount: 10,
    brewingMethod: 'nel-drip', // Cloth filter (Colador de Tela)
    brewingMethodAmount: 120,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    sweetener: 'gula-aren-cair', // Often with panela
    sweetenerAmount: 10,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 16. Italian Moka Pot Coffee
  {
    name: 'Italian Moka Pot Coffee',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 15,
    roastLevel: 'dark',
    roastLevelAmount: 15,
    brewingMethod: 'moka-pot',
    brewingMethodAmount: 100,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 18. Portuguese Galao
  {
    name: 'Portuguese Galão',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 18,
    roastLevel: 'medium',
    roastLevelAmount: 18,
    brewingMethod: 'espresso-machine',
    brewingMethodAmount: 40,
    milk: 'whole-milk',
    milkAmount: 120, // A lot of foamed milk
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 19. Austrian Einspänner
  {
    name: 'Austrian Einspänner',
    coffeeBeans: 'arabica',
    coffeeBeansAmount: 18,
    roastLevel: 'medium',
    roastLevelAmount: 18,
    brewingMethod: 'doppio',
    brewingMethodAmount: 60,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'whipped-cream', // Key ingredient
    toppingsAmount: 30,
  },
  // 24. Indian Filter Coffee
  {
    name: 'Indian Filter Coffee',
    coffeeBeans: 'robusta', // Often a blend with chicory
    coffeeBeansAmount: 15,
    roastLevel: 'dark',
    roastLevelAmount: 15,
    brewingMethod: 'indian-filter-coffee',
    brewingMethodAmount: 80,
    milk: 'whole-milk',
    milkAmount: 80,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'gula-pasir',
    sweetenerAmount: 10,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 25. Malaysian Kopi O
  {
    name: 'Malaysian Kopi O',
    coffeeBeans: 'liberica',
    coffeeBeansAmount: 15,
    roastLevel: 'dark',
    roastLevelAmount: 15,
    brewingMethod: 'kopi-tarek',
    brewingMethodAmount: 120,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'gula-pasir',
    sweetenerAmount: 15,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 26. Singapore Kopi
  {
    name: 'Singapore Kopi',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 15,
    roastLevel: 'dark',
    roastLevelAmount: 15,
    brewingMethod: 'kopi-tarek',
    brewingMethodAmount: 100,
    milk: 'skm',
    milkAmount: 30,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'none',
    toppingsAmount: 0,
  },
  // 27. Thai Traditional Coffee
  {
    name: 'Thai Traditional Coffee (Oliang)',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 20,
    roastLevel: 'dark',
    roastLevelAmount: 20,
    brewingMethod: 'kopi-tarek', // Sock filter
    brewingMethodAmount: 150,
    milk: 'skm',
    milkAmount: 30,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'simple-syrup',
    sweetenerAmount: 20,
    toppings: 'ice-cube',
    toppingsAmount: 100,
  },
  // 30. Vietnamese Iced Coffee (tanpa gula)
  {
    name: 'Vietnamese Iced Coffee (No Sugar)',
    coffeeBeans: 'robusta',
    coffeeBeansAmount: 20,
    roastLevel: 'dark',
    roastLevelAmount: 20,
    brewingMethod: 'vietnamese-drip',
    brewingMethodAmount: 100,
    milk: 'none',
    milkAmount: 0,
    creamer: 'none',
    creamerAmount: 0,
    syrup: 'none',
    syrupAmount: 0,
    sweetener: 'none',
    sweetenerAmount: 0,
    toppings: 'ice-cube',
    toppingsAmount: 120,
  },
];
